apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testapp1
  links:
    - url: https://github.com/yellowjung/source-config
      title: SoruceCode
      icon: github
  description: |
    이 애플리케이션은 SpringBoot Application 서버입니다.
  annotations:
    aws.amazon.com/aws-codebuild-project-arn: arn:aws:codebuild:ap-northeast-2:381491950219:project/github-connect
    aws.amazon.com/aws-codepipeline-arn: arn:aws:codepipeline:ap-northeast-2:381491950219:testpipe
    backstage.io/techdocs-ref: dir:../
    argocd/app-name: testapp1
    sonarqube.org/project-key: default/poc
spec:
  type: website
  owner: user:guest
  system: example
  lifecycle: experimental
  providesApisf:
    - testapp1-api
